### ISSUE TITLE
Graphing does not have an X axis

### ISSUE THREAD

**Issue by daltzctr** [Gold872/elastic-dashboard#11]
![image](https://github.com/Gold872/elastic-dashboard/assets/105223895/acfcadfe-7163-4371-9bc0-edab37bc4293)

**Comment by Gold872** [comment]
This is because of the way the graph is being rendered. It's using a ChartSeriesController to improve performance when there are a lot of widgets. This essentially has the X axis continuously increasing, and there is not a way of it to display time. If I wanted to include numbers on the X axis, it would severely slow the program down if graphs are being rendered.

**Comment by daltzctr** [comment]
The graph is not very usable without the X axis.

**Comment by Gold872** [comment]
The graph is really intended to see the general trend in how data is changing, as during matches you won't want to be looking at precise timing because there's a robot to operate. For applications where you need to precisely see things over time, I recommend using Glass's plotting feature instead.
