### ISSUE TITLE
Save & Load layout to robot

### ISSUE THREAD

**Issue by lidor51** [Gold872/elastic-dashboard#134]
We would like to save & store layout in robot (roborio), so we could effortless switch laptops and still be able to use the latest layout (without pulling code or something).
We don't really care whether it's through UI/API as long as layout is automatically loaded.

**Comment by NicholasFlamy** [comment]
To expand onto this, it'd be really great if after doing a Save As, regular saves would save to file. Having to Save As every time results in forgetting to Save As and not having the changes saved to our Git repo so we can access the changes on another device.

Ultimately, having an option to PURELY store the config in a file and load and save from it directly would be optimal. This would mean every time Elastic launches it loads from the file (rather than the local file) and every time you hit Save (such as closing the app and being prompted to save) it saves to the file. (If Elastic currently stored config in a file on disk I would symlink it to the one in the repo.)

I only have minimal Flutter experience and considering the season has started I don't know if I can contribute this.
