### ISSUE TITLE
Sendables not Draggable after beta 1

### ISSUE THREAD

**Issue by Ryanforce08** [Gold872/elastic-dashboard#141]
I have a sendable builder that used to be draggable by list before beta 1 which introduces widget registrar which i believe is the issue but after that its no longer possible. Here is the code that makes the sendable for example https://github.com/FRC5113/2024-Testing-Swerve/blob/main/magicbot/util/smart_preference.py

**Comment by DanPeled** [comment]
I have been using the elastic beta 4 yesterday and it worked, what version of elastic is this currently happening to u on?

**Comment by Ryanforce08** [comment]
It has happened on every version after beta 1

**Comment by DanPeled** [comment]
Are u able to provide a video of the behavior?

**Comment by Ryanforce08** [comment]
https://github.com/user-attachments/assets/ecfaf2b7-a2d1-4e63-9957-cbc09e6fc433

**Comment by DanPeled** [comment]
This is really odd, I just tested yesterday and it seems to work, how are u posting that topic?

**Comment by Ryanforce08** [comment]
We use sendable builder

**Comment by DanPeled** [comment]
is that the case for all the sendables or just the custom ones u made? i see u are not trying to drag the others

**Comment by Ryanforce08** [comment]
Custom ones

**Comment by DanPeled** [comment]
Then probably ur doing something wrong and not the dashboard

**Comment by Ryanforce08** [comment]
Then why would it have worked before beta

**Comment by DanPeled** [comment]
extermely unsure, but it is 90% something wrong with how u did it

**Comment by sciencewhiz** [comment]
You could try bisecting, but looking through the changes since beta 1, I'd guess this was the change: https://github.com/Gold872/elastic-dashboard/pull/110

**Comment by Ryanforce08** [comment]
> extermely unsure, but it is 90% something wrong with how u did it
> 
> Try to run that same code with the latest acutal release and not a beta one and lmk if it works

it does work and tried beta 1, which is when it stops working

**Comment by Ryanforce08** [comment]
I was looking through stuff, and I think it has to do with #43, so when I use Builder. setSmartDashboardType("SmartController") is not a built-in widget, which makes it undragable. This is just a theory though

**Comment by DanPeled** [comment]
yes, theres a high possibility its that

**Comment by Gold872** [comment]
I was finally able to reproduce this issue, what I did was started a server with outline viewer, and published data from an old log file of one of my team's matches. Initially, I noticed that no list layouts were created (none of the `.type` topics were published), however, if I held the drag for a few seconds, the widget would appear. I'm not sure if this is the exact same issue you are having, but I encourage to try holding the drag for a few seconds to see.

With this in mind though, I've come up with the following:
1. From what I tested, I don't believe there were any changes in Beta 1 that would lead to this type of behavior
2. The widget actually does get built, it just takes a long time

The issue is caused by these 2 snippets:
https://github.com/Gold872/elastic-dashboard/blob/1a993f358033874e461d728cd53f676aafd48ce1/lib/widgets/network_tree/networktables_tree_row.dart#L185-L187
By default, it will wait 2.5 seconds to receive a response, if it's a case like mine where there is no `.type` data, then it will wait before continuing, which isn't really necessary

https://github.com/Gold872/elastic-dashboard/blob/1a993f358033874e461d728cd53f676aafd48ce1/lib/widgets/network_tree/networktables_tree_row.dart#L204-L223
When creating the list layout, it will create each widget one at a time instead of doing them all at once, which further increases the list layout creation time

To fix this, I'm going to wait for all of the list layout widgets to build at once, so multiple widgets could be "fetched" at once

Regarding the `.type` issue, I can start by decreasing the timeout period, however it could also lead to "false positives" where the timeout is too low to receive any data. I'll continue looking into the solution to the timeout problem.

Try reproducing this again but instead, hold the drag for much longer and see if the widget appears

**Comment by Ryanforce08** [comment]
The widget did not appear sadly. I m going to look through code and see if I can figure what changed in beta 1

**Comment by Gold872** [comment]
Could you also send the code you are using to register this custom widget? It's possible there's an issue on that end

**Comment by Ryanforce08** [comment]
Here you go. This is the file that it's in https://github.com/FRC5113/2024-Testing-Swerve/blob/main/magicbot/util/smart_preference.py

**Comment by Gold872** [comment]
Found the issue, and it was a weird one

https://github.com/Gold872/elastic-dashboard/pull/151

Essentially what was happening was the widget type wasn't registered, so it created a "Stub" widget (used for widgets without custom properties, and since it's not a coded in widget, it wouldn't build a widget and cancel the operation. Since it was able to create a stub widget, it chose not to create a list layout, which is why nothing would be created.

Not sure what was changed after beta 1 that broke it, I'm surprised it worked before that
