### ISSUE TITLE
Submit a HomeBrew Cask

### ISSUE THREAD

**Issue by EvanLuo42** [Gold872/elastic-dashboard#21]
HomeBrew is a widely used package manager on macOS. It would be very convenient for macOS users to install if Elastic Dashboard is published on HomeBrew cask.

**Comment by Gold872** [comment]
I don't plan on publishing the program to another package manager/app store since it's another place where it has to be maintained, and I like being able to use Github for a centralized download place. The executable that the Github CI workflow compiles is also unsigned (I don't have the money to pay for an executable certificate on 3 platforms), so that could also cause some issues.
