### ISSUE TITLE
Feature request: shape differences for booleans

### ISSUE THREAD

**Issue by rjbell4** [Gold872/elastic-dashboard#32]
**Is your feature request related to a problem? Please describe.**
Color options for Boolean values are great for many of us.  But for those who are color-blind, this is more difficult.  While colors are configurable to perhaps avoid specific issues, changing _shapes_ could also be helpful.

**Describe the solution you'd like**
Instead of just "box of green" and "box of red", how about "green checkmark" and "red x", etc.  Or "green/red circle/square with black x or checkmark inlaid", etc.  Such a solution could be quickly perceived both by those with full color perception and those who are color blind.

**Describe alternatives you've considered**
Picking a different color palette; reasonable, but I think we could go further.

**Comment by Gold872** [comment]
What I was able to add is the ability to display icons instead of a rectangle. For the true condition, you can display it as a checkmark, and for false you can display it as an X or as an exclamation point. It will still show the icon in the color you selected.

Let me know if you have more ideas for the icons
