### ISSUE TITLE
Application refuses to launch if shared-preferences.json is corrupted

### ISSUE THREAD

**Issue by daltzctr** [Gold872/elastic-dashboard#9]

**Comment by daltzctr** [comment]
Located at `appdata/com.gold872/`

**Comment by Gold872** [comment]
How exactly is the shared preferences file getting corrupted? That falls a bit more into an issue with your hard drive

**Comment by daltzctr** [comment]
It's actually fairly common for json configs to be a point of error in programs. Task managering the program after it hard freezes in the middle of a write can corrupt the json.

If it fails to read, I expect it to recreate the json.

**Comment by Gold872** [comment]
Since the shared preferences is handled by a library that is not maintained by me, this is something that you will have to suggest to the maintainers of the SharedPreferences plugin.

https://pub.dev/packages/shared_preferences
https://github.com/flutter/packages/tree/main/packages/shared_preferences

**Comment by daltzctr** [comment]
Possible workaround you could do here https://github.com/flutter/flutter/issues/89211#issuecomment-915096452
